# Dockerfile.consumer
FROM python:3.8-slim

WORKDIR /app/api

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY api /app/api

CMD ["sh", "-c", "python listen_data.py & uvicorn main:app --host 0.0.0.0 --port 8000"]

